### ISSUE TITLE
model.signif() - model.pval only showing 0 for significant results

### ISSUE THREAD

**Issue by BethPoulton1995** [milesilab/BioRssay#3]
Thank you for this great package. I have been able to do almost everything I need for my data analysis but I require more digits of the p values (preferably the bonferroni adjusted values) for publication. Is it possible to amend the code to permit this? I cannot publish the results with a p value of 0 and the bonferroni correction value as just significant.

As a request for future updates, an addition which permits statistical comparison of the RR values between strains would be amazing. Thanks.

**Comment by piyalkarum** [comment]
@BethPoulton1995 
Thank you for using our package.
The function model.signif() prints the rounded (to five decimals) p-value of the model tests and pairwise comparisons as a default for efficient printing of tables. This means that if you see a p-value of 0, the actual p-value is smaller than 0.000005, which I believe you can show as <0.0001 or <0.000005 in publications. However, considering your request, I've added an option to the function to print the complete p-value. Please set full.pval to TRUE if you want to enable this option in the model.signif function. 
Note: this is only available in the github developmental option.

Regarding your suggestion about RR comparison, could you please provide more details as to what exactly you expect from a RR comparison? Maybe we can implement it if it is a useful option for other users as well.

**Comment by piyalkarum** [comment]
@BethPoulton1995 
Thank you for using our package.
The function model.signif() prints the rounded (to five decimals) p-value of the model tests and pairwise comparisons as a default for efficient printing of tables. This means that if you see a p-value of 0, the actual p-value is smaller than 0.000005, which I believe you can show as <0.0001 or <0.000005 in publications. However, considering your request, I've added an option to the function to print the complete p-value. Please set full.pval to TRUE if you want to enable this option in the model.signif function. 
Note: this is only available in the github developmental option.

Regarding your suggestion about RR comparison, could you please provide more details as to what exactly you expect from a RR comparison? Maybe we can implement it if it is a useful option for other users as well.

**Comment by piyalkarum** [comment]
@BethPoulton1995 
Thank you for using our package.
The function model.signif() prints the rounded (to five decimals) p-value of the model tests and pairwise comparisons as a default for efficient printing of tables. This means that if you see a p-value of 0, the actual p-value is smaller than 0.000005, which I believe you can show as <0.0001 or <0.000005 in publications. However, considering your request, I've added an option to the function to print the complete p-value. Please set full.pval to TRUE if you want to enable this option in the model.signif function. 
Note: this is only available in the github developmental option.

Regarding your suggestion about RR comparison, could you please provide more details as to what exactly you expect from a RR comparison? Maybe we can implement it if it is a useful option for other users as well.
